---
site_name: "juniper-mpls-l3vpn-demo"
site_description: "Deploy a L3VPN circuit over an MPLS backbone with Juniper vMX routers"
site_url: "https://aws.github.io/copilot-cli/"
site_author: "cdot65"
repo_name: "juniper-mpls-l3vpn-demo"
repo_url: "https://github.com/cdot65/juniper-mpls-l3vpn-demo"
copyright: "Copyright &copy; 2022 cdot65"
docs_dir: "site/content"
site_dir: "docs"
extra_css:
  - "stylesheets/extra.css"
extra:
  alternate:
    - name: "English"
      link: "./en/"
      lang: "en"

nav:
  - Homepage: "index.en.md"
  - Documentation:
      - Overview: "docs/overview.en.md"
      - Automation:
          - generate.py: "docs/generate.py.md"
          - configure.py: "docs/configure.py.md"
          - download.py: "docs/download.py.md"
          - rollback.py: "docs/rollback.py.md"
          - Templates: "docs/templates.py.md"
      - Network:
          - IP Addressing: "docs/ip-addressing.md"
          - MPLS: "docs/ip-addressing.md"
          - Routing: "docs/ip-addressing.md"
      - Provisioning:
          - Workflow: "docs/provisioning.md"
      - Validating:
          - Workflow: "docs/validating.md"

theme:
  name: "material"
  custom_dir: "site/overrides"
  palette:
    primary: "white"
  font: false
  icon:
    logo: "octicons/terminal-16"
  favicon: "files/images/cli.png"
  language: "en"
  features:
    - "tabs"
    - "instant"

markdown_extensions:
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - "pymdownx.tabbed"

plugins:
  - "search"
  - macros:
      include_dir: "site/content/docs/include"
