---
site_name: "juniper-mpls-l3vpn-demo"
site_author: "cdot65"
site_description: "Deploy a L3VPN circuit over an MPLS backbone with Juniper vMX routers"
docs_dir: "files/docs/"
theme:
  name: "material"
  custom_dir: "site/overrides"
  palette:
    primary: "white"
  font: false
  icon:
    logo: "octicons/terminal-16"
  favicon: "files/images/cli.png"
  language: "en"
  features:
    - "tabs"
    - "instant"
extra_css:
  - "stylesheets/extra.css"
copyright: "Copyright &copy; 2022 cdot65"
repo_name: "juniper-mpls-l3vpn-demo"
repo_url: "https://github.com/cdot65/juniper-mpls-l3vpn-demo"
use_directory_urls: true
nav:
  - Homepage: "index.md"
  - Automation:
      - generate.py: "generate.py.md"
      - configure.py: "configure.py.md"
      - download.py: "download.py.md"
      - rollback.py: "rollback.py.md"
      - Templates: "templates.py.md"
  - Network:
      - IP Addressing: "ip-addressing.md"
      - MPLS: "ip-addressing.md"
      - Routing: "ip-addressing.md"
  - Provisioning:
      - Workflow: "provisioning.md"
  - Validating:
      - Workflow: "validating.md"

markdown_extensions:
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - "pymdownx.tabbed"
  - pymdownx.emoji:
      emoji_index: "!!python/name:materialx.emoji.twemoji"
      emoji_generator: "!!python/name:materialx.emoji.to_svg"
      options:
        custom_icons:
          - "site/overrides/.icons"

plugins:
  - "search"
  - i18n:
      default_language: "en"
      languages:
        en: "english"
        ja: "japanese"
      material_alternate: false
