---
site_name: "juniper-mpls-l3vpn-demo"
site_author: "cdot65"
site_description: "Deploy a L3VPN circuit over an MPLS backbone with Juniper vMX routers"
docs_dir: "site/content"
site_dir: "docs"
repo_name: "juniper-mpls-l3vpn-demo"
repo_url: "https://github.com/cdot65/juniper-mpls-l3vpn-demo"
copyright: "Copyright &copy; 2022 cdot65"
extra_css:
  - "stylesheets/extra.css"

nav:
  - Homepage: "index.md"
  - Automation:
      - generate.py: "docs/generate.py.md"
      - configure.py: "docs/configure.py.md"
      - download.py: "docs/download.py.md"
      - rollback.py: "docs/rollback.py.md"
      - Templates: "docs/templates.py.md"
  - Network:
      - IP Addressing: "docs/ip-addressing.md"
      - MPLS: "docs/ip-addressing.md"
      - Routing: "docs/ip-addressing.md"
  - Provisioning:
      - Workflow: "docs/provisioning.md"
  - Validating:
      - Workflow: "docs/validating.md"

theme:
  name: "material"
  custom_dir: "site/overrides"
  palette:
    primary: "white"
  font: false
  icon:
    logo: "octicons/terminal-16"
  favicon: "files/images/cli.png"
  language: "en"
  features:
    - "tabs"
    - "instant"

use_directory_urls: true

markdown_extensions:
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - "pymdownx.tabbed"

plugins:
  - "search"
