---
name: "Publish docs via GitHub Pages"
on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    name: "Deploy docs"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout main"
        uses: "actions/checkout@v2"

      - name: "Deploy docs"
        uses: "mhausenblas/mkdocs-deploy-gh-pages@d576def3fd14c49606b31d3e749862f879560b37"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CONFIG_FILE: "mkdocs.yml"
          EXTRA_PACKAGES: "build-base"
          REQUIREMENTS: ".github/requirements.txt"
